// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tmuqsrcaryskjusftlaf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRtdXFzcmNhcnlza2p1c2Z0bGFmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYzNzI5NDAsImV4cCI6MjA2MTk0ODk0MH0.86Ksh_9rvossZWndmJrf6MUe5Oc4fYQvQplcEDSSE6Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);